version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./build/docker/Dockerfile
    pull_policy: never
    image: sample_ws_backend
    container_name: sample_ws_backend
    hostname: backend
    restart: always
    ports:
      - 8080:8080